---
- name: Provision OPNsense Firewall
  hosts: opnsense
  gather_facts: false

  # Setting defaults for all modules in the oxlorg.opnsense collection
  module_defaults:
    group/oxlorg.opnsense.all:
      firewall: "{{ firewall }}"
      api_key: "{{ api_key }}"
      api_secret: "{{ api_secret }}"
      ssl_verify: "{{ ssl_verify }}"

  tasks:
    - name: Load gathered configuration
      delegate_to: localhost
      ansible.builtin.include_vars:
        dir: "../input"
        name: gathered_config

    - name: Provision Aliases from gathered data
      oxlorg.opnsense.alias:
        name: "{{ item.name }}"
        type: "{{ item.type }}"
        content: "{{ item.content }}"
        description: "{{ item.description | default('') }}"
        state: present
      loop: "{{ gathered_config.alias | default([]) }}"

    - name: Provision Firewall Rules from gathered data
      oxlorg.opnsense.rule:
        interface: "{{ item.interface }}"
        direction: "{{ item.direction }}"
        ipprotocol: "{{ item.ipprotocol }}"
        protocol: "{{ item.protocol }}"
        src: "{{ item.src }}"
        dst: "{{ item.dst }}"
        dst_port: "{{ item.dst_port | default('') }}"
        description: "{{ item.description | default('') }}"
        action: "{{ item.action }}"
        state: present
      loop: "{{ gathered_config.rule | default([]) }}"

    - name: Provision NAT Source Rules from gathered data
      oxlorg.opnsense.nat_source:
        interface: "{{ item.interface }}"
        protocol: "{{ item.protocol | default('any') }}"
        src: "{{ item.src }}"
        dst: "{{ item.dst }}"
        description: "{{ item.description | default('') }}"
        state: present
      loop: "{{ gathered_config.nat_source | default([]) }}"

    - name: Provision Unbound Hosts from gathered data
      oxlorg.opnsense.unbound_host:
        host: "{{ item.host }}"
        domain: "{{ item.domain }}"
        rr: "{{ item.rr | default('A') }}"
        mxprio: "{{ item.mxprio | default(omit) }}"
        mx: "{{ item.mx | default(omit) }}"
        server: "{{ item.server }}"
        description: "{{ item.description | default('') }}"
        state: present
      loop: "{{ gathered_config.unbound_host | default([]) }}"

    - name: Apply changes (Reload)
      oxlorg.opnsense.reload:
        target: "filter"
